# configs/whisky_nl.yaml

name: 'WhiskyNL'
base_url: 'https://whisky.nl'
retailer_country: 'NL'
currency: 'EUR'
pagination_url: 'https://whisky.nl/whisky.html?p={}'
product_list_selector: '.products.wrapper.grid.products-grid'
product_item_selector: '.item.product.product-item'
fields:
  name:
    selector: '.product.name.product-item-name .product-item-link'
    parser: 'str'
  price:
    selector: '.price-box .price-wrapper[data-price-amount]'
    parser: 'float'
  original_price:
    selector: '.old-price .price-wrapper[data-price-amount]'
    parser: 'float'
  link:
    selector: '.product.photo.product-item-photo'
    parser: 'url'
    attribute: 'href'
  image_url:
    selector: '.product-image-photo'
    parser: 'url'
    attribute: 'src'
detail_fields:
  description:
    selector: '.product.attribute.overview .value'
    parser: 'str'
  volume:
    selector: '.additional-attributes-wrapper.table-wrapper tr:-soup-contains("Inhoud") td'
    parser: 'str'
  abv:
    selector: '.additional-attributes-wrapper.table-wrapper tr:-soup-contains("Alcoholpercentage") td'
    parser: 'float'
  category:
    selector: '.additional-attributes-wrapper.table-wrapper tr:-soup-contains("Categorie") td'
    parser: 'str'
  brand:
    selector: '.additional-attributes-wrapper.table-wrapper tr:-soup-contains("Merk / Distilleerderij") td'
    parser: 'str'
  country:
    selector: '.additional-attributes-wrapper.table-wrapper tr:-soup-contains("Land") td'
    parser: 'str'
  rating:
    selector: '#ratings-summary .rating-result'
    parser: 'float'
  num_reviews:
    selector: '.reviews-actions .action.view'
    parser: 'int'
  in_stock:
    selector: '.stock.available'
    parser: 'bool'
  product_id:
    selector: '.product.photo.product-item-photo[href]'
    parser: 'regex'
    pattern: '/([^/]+)\.html$' # Ensure this pattern matches the actual link format
delay: 2
retries: 3
enabled: false
