scraper_type: 'network'
sector: 'beverages'
name: 'DrankDozijn'
base_url: 'https://www.drankdozijn.nl'
retailer_country: 'NL'
currency: 'EUR'
request_url: 'https://es-api.drankdozijn.nl/products'
request_method: 'GET'
request_payload:
  country: 'NL'
  language: 'nl'
  page_template: 'groep'
  group: 'whisky'
  page: 1
  listLength: 192
  clientFilters: '{}'
  response: 'paginated'
  sorteerOp: 'relevance'
  ascdesc: 'asc'
  onlyAvail: 'false'
  cacheKey: 1
  premiumMember: 'N'

response_mapping:
  root: 'data'
  fields:
    name: 'description'
    price: 'price'
    original_price: 'salePrice'
    link: 'alias'
    volume: "features[?alias=='inhoud'].value.description | [0]"
    abv: "features[?alias=='alcoholpercentage'].value.description | [0]"
    category: "features[?alias=='categorie'].value.description | [0]"
    subcategory: "features[?alias=='smaakprofiel'].value.description | [0]"
    brand: 'brandDescription'
    country: "features[?alias=='land'].value.description | [0]"
    description: 'description'
    rating: 'reviewScore'
    num_reviews: 'reviewCount'
    in_stock: 'availability'
    image_url: 'structuredData.image[0]'
    product_id: 'ean'
    series: "features[?alias=='serie'].value.description | [0]"

delay: 2
retries: 3
enabled: true
