name: 'HeinemannShop'
base_url: 'https://www.heinemann-shop.com'
retailer_country: 'DE'
currency: 'EUR'
pagination_url: 'https://www.heinemann-shop.com/en/global/whisky/c/cat_5150/?q=%3Arelevance&page={}'
product_list_selector: '.c-product-listing'
product_item_selector: '.c-product-card'
fields:
  name:
    selector: '.c-product-card__headline'
    parser: 'str'
  price:
    selector: '.c-price-box .c-price'
    parser: 'float'
  original_price:
    selector: '.c-price-box__old-price'
    parser: 'float'
  link:
    selector: '.c-product-card__link'
    parser: 'url'
    attribute: 'href'
  image_url:
    selector: '.c-product-card__image img'
    parser: 'url'
    attribute: 'src'
detail_fields:
  description:
    selector: '.c-accordion__content p'
    parser: 'str'
  volume:
    selector: '.c-product-details-table tr:-soup-contains("Volume") td'
    parser: 'str'
  abv:
    selector: '.c-product-details-table tr:-soup-contains("Alcohol by Volume") td'
    parser: 'float'
  category:
    selector: '.c-product-details-table tr:-soup-contains("Trade Name") .c-product-details-table__value'
    parser: 'str'
  brand:
    selector: '.c-product-details-table tr:-soup-contains("Manufacturer Information") .c-product-details-table__value'
    parser: 'str'
  country:
    selector: '.c-product-details-table tr:-soup-contains("Country of Origin") .c-product-details-table__value'
    parser: 'str'
  region:
    selector: '.c-product-details-table tr:-soup-contains("Whisky Region") .c-product-details-table__value'
    parser: 'str'
  rating:
    selector: '#ratings-summary .rating-result'
    parser: 'float'
  num_reviews:
    selector: '.reviews-actions .action.view'
    parser: 'int'
  in_stock:
    selector: '.c-stock-display__state'
    parser: 'bool'
  product_id:
    selector: '.c-product-details-table tr:-soup-contains("Item No.") .c-product-details-table__value'
    parser: 'str'
delay: 2
retries: 3
enabled: false
