name: 'HeinemannShop'
base_url: 'https://www.heinemann-shop.com'
retailer_country: 'DE'
currency: 'EUR'
pagination_url: 'https://www.heinemann-shop.com/en/global/whisky/c/cat_5150/?q=%3Arelevance&page={}'
product_list_selector: '.c-product-listing'
product_item_selector: '.c-product-card'
name_selector: '.c-product-card__headline'
price_selector: '.c-price-box .c-price'
original_price_selector: '.c-price-box__old-price'
link_selector: '.c-product-card__link'
image_selector: '.c-product-card__image'
next_page_selector: '.c-pagination-bar__item:last-child .c-pagination-bar__button'
detail_info_selector: '.c-product-preview'
description_selector: '.c-accordion__content p'
product_details_table_selector: '.c-product-details-table'
in_stock_selector: '.c-stock-display__state'
product_image_selector: '.c-product-preview__large-image img'
delay: 2
retries: 3
