name: 'WhiskyNL'
base_url: 'https://whisky.nl'
retailer_country: 'NL'
currency: 'EUR'
pagination_url: 'https://whisky.nl/whisky.html?p={}'
product_list_selector: '.products.wrapper.grid.products-grid'
product_item_selector: '.item.product.product-item'
name_selector: '.product.name.product-item-name .product-item-link'
price_selector: '.price-box .price-wrapper'
original_price_selector: '.old-price .price-wrapper'
link_selector: '.product.photo.product-item-photo'
image_selector: '.product-image-photo'
next_page_selector: '.pages-item-next'
detail_info_selector: '.additional-attributes-wrapper.table-wrapper'
description_selector: '.product.attribute.overview .value'
rating_selector: '#ratings-summary .rating-result'
review_count_selector: '.reviews-actions .action.view'
in_stock_selector: '.stock.available'
delay: 2
retries: 3
